# Generated by Django 4.0.3 on 2022-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('START_DATE', models.CharField(max_length=300)),
                ('START_DATE_TIMESTAMP', models.BigIntegerField()),
                ('END_DATE', models.CharField(max_length=300)),
                ('END_DATA_TIMESTAMP', models.BigIntegerField()),
                ('EVENT_NAME', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='leave_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_ID', models.CharField(max_length=300)),
                ('DURATION_TYPE', models.CharField(max_length=1)),
                ('START_DATE', models.CharField(max_length=300)),
                ('START_DATE_TIMESTAMP', models.BigIntegerField()),
                ('END_DATE', models.CharField(max_length=300)),
                ('END_DATE_TIMESTAMP', models.BigIntegerField()),
                ('TYPE', models.CharField(max_length=1)),
                ('REASON', models.TextField()),
                ('STATUS', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='overtime_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPT_ID', models.CharField(max_length=300)),
                ('WORK_TYPE', models.CharField(max_length=1)),
                ('DURATION', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='task_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_ID', models.CharField(max_length=300)),
                ('DATE', models.CharField(max_length=300)),
                ('DATE_TIMESTAMP', models.BigIntegerField()),
                ('TASK', models.TextField()),
                ('PROJECT', models.CharField(max_length=300)),
                ('PROJECT_COLOR', models.CharField(max_length=300)),
                ('REMARKS', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='timesheet_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_ID', models.CharField(max_length=300)),
                ('CLOCK_IN', models.BigIntegerField()),
                ('CLOCK_IN_TIMESTAMP', models.BigIntegerField()),
                ('CLOCK_OUT', models.BigIntegerField()),
                ('CLOCK_OUT_TIMESTAMP', models.BigIntegerField()),
                ('WORK_TYPE', models.CharField(max_length=1)),
                ('SHOW_VALIDATION', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_ID', models.CharField(max_length=300)),
                ('NAME', models.CharField(max_length=300)),
                ('DESIGNATION', models.CharField(max_length=300)),
                ('EMAIL', models.CharField(max_length=300)),
                ('PASSWORD', models.CharField(max_length=300)),
                ('JOINING_DATE', models.CharField(max_length=300)),
                ('JOINING_DATE_TIMESTAMP', models.BigIntegerField()),
            ],
        ),
    ]
