# Generated by Django 4.0.3 on 2022-09-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='TOKEN',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='USER_TYPE',
            field=models.CharField(default='U', max_length=1),
            preserve_default=False,
        ),
    ]
