# Generated by Django 4.0.3 on 2022-09-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_overtime_log_date_overtime_log_date_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtime_log',
            old_name='EMPT_ID',
            new_name='EMP_ID',
        ),
    ]
