# Generated by Django 4.0.3 on 2022-09-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_rename_empt_id_overtime_log_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet_log',
            name='DATE',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheet_log',
            name='CLOCK_IN',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='timesheet_log',
            name='CLOCK_OUT',
            field=models.CharField(max_length=300),
        ),
    ]
