# Generated by Django 4.0.3 on 2022-09-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_alter_event_log_end_data_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_log',
            name='DURATION',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='timesheet_log',
            name='SHOW_VALIDATION',
            field=models.IntegerField(blank=True),
        ),
    ]
