# Generated by Django 4.0.3 on 2022-09-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0010_alter_leave_log_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet_log',
            name='DAY_TYPE',
            field=models.CharField(default='W', max_length=1),
            preserve_default=False,
        ),
    ]
