# Generated by Django 4.0.3 on 2022-09-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0011_timesheet_log_day_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet_log',
            name='DURATION',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
