# Generated by Django 4.0.3 on 2022-09-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0012_timesheet_log_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_ID', models.CharField(max_length=300, null=True)),
                ('PROJECT', models.CharField(max_length=300, null=True)),
                ('STATUS', models.CharField(max_length=1, null=True)),
                ('PROJECT_COLOR', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event_log',
            name='END_DATE',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event_log',
            name='EVENT_NAME',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event_log',
            name='START_DATE',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='leave_log',
            name='DURATION_TYPE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='leave_log',
            name='EMP_ID',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='leave_log',
            name='END_DATE',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='leave_log',
            name='START_DATE',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='leave_log',
            name='STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='leave_log',
            name='TYPE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_log',
            name='DATE',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_log',
            name='EMP_ID',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_log',
            name='WORK_TYPE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='task_log',
            name='DATE',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='task_log',
            name='EMP_ID',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='task_log',
            name='PROJECT',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='task_log',
            name='PROJECT_COLOR',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='task_log',
            name='REMARKS',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet_log',
            name='CLOCK_IN',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet_log',
            name='CLOCK_OUT',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet_log',
            name='DAY_TYPE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet_log',
            name='EMP_ID',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet_log',
            name='WORK_TYPE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='DESIGNATION',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='EMAIL',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='EMP_ID',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='JOINING_DATE',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='NAME',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='PASSWORD',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='TOKEN',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='USER_TYPE',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
